spring.application.name=tp
server.port=9090



# Optionnel: afficher les requetes SQL
spring.jpa.show-sql=true

# Configuration MySQL (decommenter pour utiliser MySQL)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
